# Generated by Django 4.1.1 on 2022-09-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('general', 'General'), ('sports', 'Sports'), ('politics', 'Politics'), ('technology', 'Technology')], default='general', max_length=16),
        ),
    ]
