# Generated by Django 4.1.1 on 2022-09-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_postview_post_postview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postView',
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.post'),
        ),
    ]
